<header>
        <div class="top-bar">
            <div class="container">
                <span class="phone-no">Toll Free: <a href="tel:18002090400">1800 209 0400</a> / <a href="tel:09867565599">098675 65599</a></span>
                
                <a href="#" class="top-toggle-btn"><span></span><span></span><span></span></a>
                <div class="right-top-bar">
                    
                    
                    <div class="account-status">
                        <label>Welcome Piramal Travels</label>
                        <div class="bal-cr">
                            <div class="balance-amt">
                                <em>Bal.</em>
                                <div class="price">
                                    <i class="fa fa-inr" aria-hidden="true"></i>
                                    <span class="amt">35,000</span>
                                </div>
                                <span class="clear"></span>
                            </div>
                            <div class="credit-amt">
                                <em>Cr.</em>
                                <div class="price">
                                    <i class="fa fa-inr" aria-hidden="true"></i>
                                    <span class="amt">10,000</span>
                                </div>
                                <span class="clear"></span>
                            </div>
                            <span class="clear"></span>
                        </div>
                        <span class="clear"></span>
                    </div>
                    
                    <div class="login after-lgn">
                        <a href="#" class="dropdown-toggle" id="dropdownMenu3a" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            <span>
								<span class="author-img">
                                    <img src="/dmc/resources/images/common/user.png" alt="">
                                    <!--<img src="/dmc/resources/images/common/icons/fa-custom-login-white.png" alt="">-->
                                </span>
								<span class="after-lgn-txt">John Doe</span>
								<span class="before-lgn-txt">Login</span>
                                <i class="fa fa-angle-down"></i>
							</span>
						</a>
                        <div class="dropdown-menu theme-03">
                        <!--<div class="dropdown-menu theme-03 login-sec logout-sec">-->
                            <ul>
								<li class="before-lgn-txt login-sec">
									<a href="#" class="btn btn-primary login-btn">LOGIN</a>
									<p class="no-account">Don’t have an account yet?</p>
									<a href="#" class="btn btn-create-account">Create an account</a>
								</li>
								<li class="after-lgn-txt"><a href="#" class="cont-wrap"><i class="fa-angle-right"></i>My Profile</a></li>
                                <li class="after-lgn-txt"><a href="#" class="cont-wrap"><i class="fa-angle-right"></i>My Bookings</a></li>
                                <li><a href="#" class="cont-wrap"><i class="fa-angle-right"></i>Manage Booking</a></li>
								<li class="after-lgn-txt"><a href="#" class="cont-wrap"><i class="fa-angle-right"></i>e-Wallet</a></li>
								<li><a href="#" class="cont-wrap"><i class="fa-angle-right"></i>Fare Alerts</a></li>
								<li><a href="#" class="cont-wrap"><i class="fa-angle-right"></i>Flight Status</a></li>
								<li class="after-lgn-txt"><a href="#" class="cont-wrap btn-logout"><i class="fa-angle-right"></i>Logout</a></li>
							</ul>
                        </div>
                    </div>  
                </div>
            </div>
        </div>
        <div class="main-header">
            <div class="container">
                <div class="logo-div">
                	<a href="#" class="ck-logo"><img src="/dmc/resources/images/common/ck-logo.png" alt="Cox and Kings Logo"></a>
                </div>
                <a href="#" class="menu-btn"><span></span><span></span><span></span></a>
                <nav class="navigation">
                    <ul>
<!--                        <li class="mail-nav"><a href="#">Mail<span>8</span></a></li>-->
                        <li class="sales-nav"><a href="#">Sales</a></li>
                        <li class="booking-nav"><a href="#">Booking</a></li>
                        <li class="agent-nav"><a href="#">Agent</a></li>
                        <li class="product-nav"><a href="#">Product</a></li>
                        <li class="mis-nav"><a href="#">MIS</a></li>
                    </ul>
                </nav>
                <span class="clear"></span>
            </div>
        </div>  
    </header>