<link href="~/resources/css/bootstrap.min.css" rel="stylesheet"><!-- Bootstrap core CSS -->
<link href="~/resources/css/plugin.css" rel="stylesheet" type="text/css" media="all" /><!-- icons -->

<!-- Custom styles for this template -->
<link href="~/resources/css/master.css" rel="stylesheet">

<!-- HTML5 shiv and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="/dmc/resources/js/ie/html5shiv.js"></script>
  <script type="text/javascript" src="/dmc/resources/js/ie/PIE.js"></script>
  <script src="/dmc/resources/js/ie/respond.min.js"></script>

<![endif]-->